version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  crawler:
    build:
      context: .
    container_name: crawler-dev
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always